export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE';

// get danh mục
export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE';

// sarn pham theo danh muc

export const GET_PRODUCTS_BY_ID_CATEGORY_SUCCESS =
  'GET_PRODUCTS_BY_ID_CATEGORY_SUCCESS';
export const GET_PRODUCTS_BY_ID_CATEGORY_REQUEST =
  'GET_PRODUCTS_BY_ID_CATEGORY_REQUEST';
export const GET_PRODUCTS_BY_ID_CATEGORY_FAILURE =
  'GET_PRODUCTS_BY_ID_CATEGORY_FAILURE';

// chi tiết sản phẩm

export const DETAIL_PRODUCT_REQUEST = 'DETAIL_PRODUCT_REQUEST';
export const DETAIL_PRODUCT_SUCCESS = 'DETAIL_PRODUCT_SUCCESS';
export const DETAIL_PRODUCT_FAILURE = 'DETAIL_PRODUCT_FAILURE';

// get sản phẩm theo doanh nghiệp
export const GET_PRODUCT_BY_ID_COMPANY_REQUEST =
  'GET_PRODUCT_BY_ID_COMPANY_REQUEST';
export const GET_PRODUCT_BY_ID_COMPANY_SUCCESS =
  'GET_PRODUCT_BY_ID_COMPANY_SUCCESS';
export const GET_PRODUCT_BY_ID_COMPANY_FAILURE =
  'GET_PRODUCT_BY_ID_COMPANY_FAILURE';

//get sản phẩm gợi ý
export const GET_PRODUCT_SUGGEST_REQUEST = 'GET_PRODUCT_BY_ID_COMPANY_REQUEST';
export const GET_PRODUCT_SUGGEST_SUCCESS = 'GET_PRODUCT_SUGGEST_SUCCESS';
export const GET_PRODUCT_SUGGEST_FAILURE = 'GET_PRODUCT_SUGGEST_FAILURE';

// tìm kiếm sản phẩm

export const SEARCH_PRODUCT_REQUEST = 'SEARCH_PRODUCT_REQUEST';

export const SEARCH_PRODUCT_REQUEST_MORE = 'SEARCH_PRODUCT_REQUEST_MORE';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_SUCCESS_MORE = 'SEARCH_PRODUCT_MORE_SUCCESS';
export const SEARCH_PRODUCT_FAILURE = 'SEARCH_PRODUCT_FAILURE';
export const SEARCH_PRODUCT_FAILURE_MORE = 'SEARCH_PRODUCT_MORE_FAILED';
export const CLEAR_DATA = 'CLEAR_DATA';



export const MAIN_PRODUCT_REQUEST = 'MAIN_PRODUCT_REQUEST';

export const MAIN_PRODUCT_REQUEST_MORE = 'MAIN_PRODUCT_REQUEST_MORE';
export const MAIN_PRODUCT_SUCCESS = 'MAIN_PRODUCT_SUCCESS';
export const MAIN_PRODUCT_SUCCESS_MORE = 'MAIN_PRODUCT_MORE_SUCCESS';
export const MAIN_PRODUCT_FAILURE = 'MAIN_PRODUCT_FAILURE';
export const MAIN_PRODUCT_FAILURE_MORE = 'MAIN_PRODUCT_MORE_FAILED';
export const MAIN_CLEAR_DATA = 'MAIN_CLEAR_DATA';


// get sàn TMĐT
export const GET_ECOM_SUCCESS = 'GET_ECOM_SUCCESS';
export const GET_ECOM_FAILURE = 'GET_ECOM_FAILURE';
